name: PotionFixer
main: dev.maxwellrose1019.potionfixer.Main
version: 1.1.2
api-version: 1.13
load: STARTUP
author: MaxwellRose1019
description: Fixes broken potion names and effects for Eaglercraft clients.
softdepend: [ProtocolLib]
commands:
  testpotion:
    description: Applies PotionFixer formatting to the item in your hand.
    usage: /testpotion
    permission: potionfixer.test
permissions:
  potionfixer.test:
    description: Allows use of /testpotion
    default: op