# - - - - - - - - - - - - - - - - - - - - - - - - - - #
# ______     _   _            ______ _                #
# | ___ \   | | (_)           |  ___(_)               #
# | |_/ /__ | |_ _  ___  _ __ | |_   ___  _____ _ __  #
# |  __/ _ \| __| |/ _ \| '_ \|  _| | \ \/ / _ \ '__| #
# | | | (_) | |_| | (_) | | | | |   | |>  <  __/ |    #
# \_|  \___/ \__|_|\___/|_| |_\_|   |_/_/\_\___|_|    #
#                                                     #
# - - - - - - - - - - - - - - - - - - - - - - - - - - #


# Enable debug mode? Debug mode logs (in console) what is actively happening with the plugin.
#               default settings:
#                   debug: false
debug: false

# Strip NBT data? Clears the "No effects" and other NBT data for cleaner potion displays.
# WARNING: This may cause errors in potion displays, use, and NBT data. Use at your own risk.
#               default settings:
#                   strip-nbt: true
strip-nbt: true