name: PotionFixer
main: dev.maxwellrose1019.potionfixer.Main
version: 1.0.2
api-version: 1.13
load: STARTUP
author: MaxwellRose1019
description: Fixes broken potion names and effects for Eaglercraft clients.
softdepend: [ProtocolLib]
